# No `set shell` override, deliberately: matches the shared dev-platform
# convention (see link108/cutty-bangerz's justfile for the incident that
# motivated it) - `just`'s own default, plain POSIX `sh -cu`, is the one
# thing guaranteed present in every environment this might run in, so
# every recipe here is POSIX `sh`-compatible.

image_name := "byah-site"
container_name := "byah-site"
port := "8080"
db_name := "byah"

# Read from the Compose secret mount - only valid inside the Dev
# Container. Generated once per workspace by .devcontainer/generate-secrets.sh
# and reused across restarts/rebuilds; never regenerated by `just`.
#
# database_url respects an already-set DATABASE_URL env var first: a real
# production DATABASE_URL (from a k8s Secret) should always win over the
# local Compose default, which has no /run/secrets/* at all outside this
# workspace's own containers. Always computing a local default
# unconditionally would silently override that and break production
# migrations - see link108/cutty-bangerz's justfile for the incident that
# taught us this the hard way.

postgres_user := `cat /run/secrets/postgres_user 2>/dev/null || true`
postgres_password := `cat /run/secrets/postgres_password 2>/dev/null || true`
database_url := env_var_or_default("DATABASE_URL", "postgresql://" + postgres_user + ":" + postgres_password + "@postgres:5432/" + db_name)

default:
    @just --list

# --- Run ----------------------------------------------------------------------

# Install exact JavaScript dependencies.
install:
    npm install

# First-time setup inside a freshly created Dev Container.
setup: install generate migrate seed
    @echo "Ready. Run: just dev"

# Start the development server with hot reload.
dev: history
    DATABASE_URL="{{ database_url }}" npm run dev

# Build the static site.
build: history
    DATABASE_URL="{{ database_url }}" npm run build

# Snapshot each content file's git history into src/generated/history.json
# (read by VersionHistory.astro). Needs full git history to be meaningful -
# see .woodpecker.yaml's clone depth for why CI runs this before docker-build
# rather than inside the Docker image.
history:
    npm run history:generate

# --- Database -----------------------------------------------------------------

# Regenerate the Prisma client
generate:
    npx prisma generate

# Apply migrations (migrate deploy — never `migrate dev` in this repo; author new
# migrations locally with `npx prisma migrate dev --name X` and commit the result)
migrate:
    DATABASE_URL="{{ database_url }}" npx prisma migrate deploy

# Seed breweries, BBQ teams, and default food items
seed:
    DATABASE_URL="{{ database_url }}" npx prisma db seed

# Open a psql shell against DATABASE_URL
psql:
    psql "{{ database_url }}"

# --- Quality ------------------------------------------------------------------

lint:
    npm run lint

typecheck:
    npm run typecheck

# Canonical local validation.
alias ci := check

check: generate lint typecheck build

# --- Docker ---------------------------------------------------------------

docker-build:
    docker build -t {{ image_name }} .

docker-stop:
    docker stop {{ container_name }} || true

docker-start:
    docker run -d --rm --name {{ container_name }} -p {{ port }}:80 {{ image_name }}

docker-logs:
    docker logs -f {{ container_name }}
